version: '3.9'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  JWTS: "${JWTS}"
  MONGO_DB_PRO: "${MONGO_DB_PRO}"
  TWILIO_ACCOUNT_ID: "${TWILIO_ACCOUNT_ID}"
  TWILIO_ACCOUNT_SECRET: "${TWILIO_ACCOUNT_SECRET}"
  SENDER_NUMBER: "+16097579519"
  APNS_KEY_ID: "${APNS_KEY_ID}"
  APNS_PRIVATE_KEY: "${APNS_PRIVATE_KEY}"
  APNS_TEAM_ID: "${APNS_TEAM_ID}"
  APNS_TOPIC: "com.addame.AddaMeIOS"


services:
  mongo:
    image: mongo:5.0.3
    container_name: addame_mongodb
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb/data:/data/db
    environment:
      MONGO_INITDB_DATABASE: addame_api_pro
    networks:
      - production_gateway
    restart: unless-stopped

  addame_server:
    image: addamespb/addame_server:latest
    container_name: agateway
    build:
      context: addameServer
    environment:
      <<: *shared_environment
    ports:
      - '80:8080'
      - '443:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
    volumes:
      - ~/addameServer:/addameServer_data
      - ./.env:/app/.env
      - ./.env.production:/app/.env.production
    networks:
      - production_gateway
    restart: unless-stopped

volumes:
  addameServer:

networks:
  production_gateway:
    name: Default

